import type { Command } from '@/components/action-center/CommandButton'

export const DEFAULT_COMMANDS: Command[] = [
  // ── Audit ──────────────────────────────────────────────────────────────────
  {
    id: 'audit.code-quality',
    title: 'Code Quality Audit',
    description: 'Run a full code quality audit across the active project: lint, complexity, duplication.',
    category: 'Audit',
    iconName: 'Search',
    shortcut: '⌘⇧A',
    permission: 'developer',
    agentTarget: 'architect',
  },
  {
    id: 'audit.security',
    title: 'Security Scan',
    description: 'Run SAST/dependency vulnerability scan on the current codebase.',
    category: 'Audit',
    iconName: 'ShieldCheck',
    shortcut: '⌘⇧S',
    permission: 'developer',
    agentTarget: 'watcher',
  },
  {
    id: 'audit.accessibility',
    title: 'Accessibility Audit',
    description: 'Run WCAG 2.1 AA compliance audit on all UI components.',
    category: 'Audit',
    iconName: 'Eye',
    permission: 'developer',
    agentTarget: 'qa',
  },
  {
    id: 'audit.performance',
    title: 'Performance Audit',
    description: 'Lighthouse performance audit on all public routes.',
    category: 'Audit',
    iconName: 'Gauge',
    permission: 'developer',
    agentTarget: 'qa',
  },

  // ── Build ──────────────────────────────────────────────────────────────────
  {
    id: 'build.full',
    title: 'Full Build',
    description: 'Trigger a complete build of the active project including type-check, lint, and bundle.',
    category: 'Build',
    iconName: 'Hammer',
    shortcut: '⌘B',
    permission: 'developer',
    agentTarget: 'builder',
  },
  {
    id: 'build.api',
    title: 'Build API Layer',
    description: 'Generate and build only the API routes and server-side logic.',
    category: 'Build',
    iconName: 'Server',
    permission: 'developer',
    agentTarget: 'builder',
  },
  {
    id: 'build.frontend',
    title: 'Build Frontend',
    description: 'Build the frontend application with Vite/Next.js.',
    category: 'Build',
    iconName: 'LayoutDashboard',
    permission: 'developer',
    agentTarget: 'builder',
  },
  {
    id: 'build.database',
    title: 'Run Migrations',
    description: 'Apply all pending database migrations in sequence.',
    category: 'Build',
    iconName: 'Database',
    permission: 'developer',
    agentTarget: 'builder',
  },
  {
    id: 'build.schema',
    title: 'Generate Schema',
    description: 'Run architect agent to generate Zod schemas and TypeScript types.',
    category: 'Build',
    iconName: 'FileJson',
    permission: 'developer',
    agentTarget: 'architect',
  },

  // ── Design ────────────────────────────────────────────────────────────────
  {
    id: 'design.ui',
    title: 'Generate UI',
    description: 'Generate a new UI component from design spec using the design agent.',
    category: 'Design',
    iconName: 'Brush',
    permission: 'developer',
    agentTarget: 'designer',
  },
  {
    id: 'design.tokens',
    title: 'Export Design Tokens',
    description: 'Export current design tokens to CSS variables and Tailwind config.',
    category: 'Design',
    iconName: 'Palette',
    permission: 'developer',
    agentTarget: 'designer',
  },
  {
    id: 'design.mockup',
    title: 'Generate Mockup',
    description: 'Create a Figma-compatible layout mockup from feature spec.',
    category: 'Design',
    iconName: 'MonitorSmartphone',
    permission: 'developer',
    agentTarget: 'designer',
  },

  // ── QA ────────────────────────────────────────────────────────────────────
  {
    id: 'qa.unit-tests',
    title: 'Run Unit Tests',
    description: 'Execute the full unit test suite with coverage report.',
    category: 'QA',
    iconName: 'TestTube2',
    shortcut: '⌘T',
    permission: 'developer',
    agentTarget: 'qa',
  },
  {
    id: 'qa.integration-tests',
    title: 'Integration Tests',
    description: 'Run end-to-end integration tests against the staging environment.',
    category: 'QA',
    iconName: 'Beaker',
    permission: 'developer',
    agentTarget: 'qa',
  },
  {
    id: 'qa.judge-review',
    title: 'Judge Review',
    description: 'Trigger the Judge agent to evaluate the project against UDEC/MOT/ACC criteria.',
    category: 'QA',
    iconName: 'Scale',
    permission: 'developer',
    agentTarget: 'judge',
  },
  {
    id: 'qa.smoke-test',
    title: 'Smoke Test',
    description: 'Run a quick smoke test on the 5 most critical user flows.',
    category: 'QA',
    iconName: 'Flame',
    permission: 'developer',
    agentTarget: 'qa',
  },

  // ── Deploy ────────────────────────────────────────────────────────────────
  {
    id: 'deploy.staging',
    title: 'Deploy to Staging',
    description: 'Deploy the current build to the staging environment.',
    category: 'Deploy',
    iconName: 'Rocket',
    shortcut: '⌘⇧D',
    permission: 'developer',
    agentTarget: 'postman',
  },
  {
    id: 'deploy.production',
    title: 'Deploy to Production',
    description: 'Deploy to production — requires human approval before execution.',
    category: 'Deploy',
    iconName: 'Globe',
    permission: 'admin',
    agentTarget: 'postman',
  },
  {
    id: 'deploy.rollback',
    title: 'Rollback',
    description: 'Rollback to the previous stable production deployment.',
    category: 'Deploy',
    iconName: 'RotateCcw',
    permission: 'admin',
    agentTarget: 'postman',
  },
  {
    id: 'deploy.preview',
    title: 'Deploy Preview',
    description: 'Create a Vercel preview deployment from the current branch.',
    category: 'Deploy',
    iconName: 'ExternalLink',
    permission: 'developer',
    agentTarget: 'postman',
  },

  // ── Monetize ──────────────────────────────────────────────────────────────
  {
    id: 'monetize.pricing',
    title: 'Analyze Pricing',
    description: 'Run pricing analysis agent to evaluate optimal price points.',
    category: 'Monetize',
    iconName: 'DollarSign',
    permission: 'developer',
    agentTarget: 'monetize',
  },
  {
    id: 'monetize.stripe-setup',
    title: 'Setup Stripe',
    description: 'Configure Stripe products, prices, and webhooks for the active project.',
    category: 'Monetize',
    iconName: 'CreditCard',
    permission: 'admin',
    agentTarget: 'monetize',
  },
  {
    id: 'monetize.revenue-report',
    title: 'Revenue Report',
    description: 'Generate a revenue projection report based on current metrics.',
    category: 'Monetize',
    iconName: 'TrendingUp',
    permission: 'developer',
    agentTarget: 'monetize',
  },

  // ── Monitor ───────────────────────────────────────────────────────────────
  {
    id: 'monitor.health',
    title: 'System Health Check',
    description: 'Run a full health check across all agents and services.',
    category: 'Monitor',
    iconName: 'Heart',
    permission: 'all',
    agentTarget: 'watcher',
  },
  {
    id: 'monitor.logs',
    title: 'View Agent Logs',
    description: 'Open aggregated agent logs for the last 24 hours.',
    category: 'Monitor',
    iconName: 'FileText',
    permission: 'all',
    agentTarget: 'watcher',
  },
  {
    id: 'monitor.costs',
    title: 'Cost Dashboard',
    description: 'View token usage and API cost breakdown by agent and project.',
    category: 'Monitor',
    iconName: 'BarChart2',
    permission: 'admin',
    agentTarget: 'watcher',
  },
  {
    id: 'monitor.alerts',
    title: 'Configure Alerts',
    description: 'Configure Watcher alert thresholds for cost, loops, and failures.',
    category: 'Monitor',
    iconName: 'Bell',
    permission: 'admin',
    agentTarget: 'watcher',
  },
]
