import * as fs from "node:fs";
import * as path from "node:path";
import type { Company, CompanySignalBrief, Geo, ScoredSignal } from "../types.js";

const COMPANY_GEO_MAP: Record<Company, Geo> = {
  "macs-digital": "us",
  "pauli-effect": "us",
  "kupuri-media": "mx",
  cheggie: "rs",
  "myweb-lane": "in",
  "cascadia-atlas": "us",
};

const GEO_TOPIC_FOCUS: Record<Geo, string[]> = {
  us: ["B2B growth", "productivity", "AI tools", "entrepreneurship", "personal branding"],
  mx: ["negocios", "emprendimiento", "vida familiar", "tecnología", "contenido local"],
  rs: ["tech career", "EU market", "startup", "digital services", "remote work"],
  in: ["website design", "digital business", "Hindi tutorial", "SMB tech", "freelancing India"],
  global: ["AI", "creator economy", "digital nomad", "growth hacking"],
};

const buildReadyHooks = (top: ScoredSignal[]): string[] => {
  return top.slice(0, 3).map((s) => {
    const hook = s.hookText ?? s.title.slice(0, 80);
    return `[${s.hookType.toUpperCase()} hook, ${s.platform}] "${hook}"`;
  });
};

const buildFormatTemplates = (top: ScoredSignal[]): string[] => {
  const formatCounts = new Map<string, number>();
  for (const s of top) {
    const fmt = s.format ?? "unknown";
    formatCounts.set(fmt, (formatCounts.get(fmt) ?? 0) + 1);
  }
  return [...formatCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 2)
    .map(([fmt, count]) => `${fmt} (appeared in ${count} of top ${top.length} posts)`);
};

const buildAvoidThis = (all: ScoredSignal[]): string => {
  const bottom = all.slice(-5);
  const dominant = bottom.reduce(
    (acc, s) => {
      const key = `${s.hookType}+${s.format ?? "?"}`;
      acc[key] = (acc[key] ?? 0) + 1;
      return acc;
    },
    {} as Record<string, number>,
  );
  const worst = Object.entries(dominant).sort((a, b) => b[1] - a[1])[0];
  return worst ? `${worst[0]} format (low engagement this cycle)` : "No clear trend to avoid";
};

export const synthesizeCompanyBrief = (
  company: Company,
  allSignals: ScoredSignal[],
  date: string,
): CompanySignalBrief => {
  const geo = COMPANY_GEO_MAP[company];
  const geoSignals = allSignals
    .filter((s) => s.geo === geo || s.geo === "global")
    .sort((a, b) => b.viralScore - a.viralScore);
  const top = geoSignals.slice(0, 10);

  const topicFocus = GEO_TOPIC_FOCUS[geo] ?? GEO_TOPIC_FOCUS.global;
  const topPatterns = top.slice(0, 5).map((s) => ({
    hookType: s.hookType,
    format: s.format ?? "unknown",
    topic: topicFocus[Math.floor(Math.random() * topicFocus.length)],
    viralScore: Math.round(s.viralScore * 1000) / 1000,
  }));

  return {
    company,
    date,
    geo,
    topPatterns,
    readyHooks: buildReadyHooks(top),
    formatTemplates: buildFormatTemplates(top),
    avoidThis: buildAvoidThis(geoSignals),
    rawSignalCount: geoSignals.length,
  };
};

export const writeBriefToSignalsFolder = (
  brief: CompanySignalBrief,
  repoRoot: string,
): void => {
  const signalsDir = path.join(repoRoot, "companies", brief.company, "_signals");
  fs.mkdirSync(signalsDir, { recursive: true });

  const content = `# ${brief.company} — Signal Brief
**Date:** ${brief.date}
**Geo:** ${brief.geo.toUpperCase()}
**Signals analyzed:** ${brief.rawSignalCount}

## Top 5 Patterns This Cycle

${brief.topPatterns
  .map(
    (p, i) =>
      `${i + 1}. **${p.hookType} hook** · Format: ${p.format} · Topic: ${p.topic} · Score: ${p.viralScore}`,
  )
  .join("\n")}

## Ready-to-Adapt Hooks

${brief.readyHooks.map((h) => `- ${h}`).join("\n")}

## Winning Formats

${brief.formatTemplates.map((f) => `- ${f}`).join("\n")}

## Avoid This Cycle

- ${brief.avoidThis}

---
*Generated by PAULI Content Engine — read before drafting any content.*
`;

  fs.writeFileSync(path.join(signalsDir, "today.md"), content, "utf-8");
};
