export const UI_INTELLIGENCE_SKILL = {
  id: 'ui_intelligence',
  name: 'UI Intelligence',
  description: 'Full browser tour, design system extraction, journey mapping, doc rewriting, and React component generation for any web app',
  version: '1.0.0',
  folder: 'skills/ui-intelligence/',
  outputPath: 'factory/ui-analyses/',
  triggerPhrases: [
    'analyze this app',
    'analyze this UI',
    'analyze https',
    'document the UI',
    'take a tour of this product',
    'rebuild this interface',
    'extract the design system',
    'generate components for',
    'document how this app works',
    'map the user journey',
  ],
  requiredInputs: ['url', 'credentials?', 'priorityFlows?'],
  phases: [
    { id: 1, name: 'Initialize and Log In' },
    { id: 2, name: 'Extract the Design System' },
    { id: 3, name: 'Map the Entire User Journey' },
    { id: 4, name: 'Deep Dive on Microinteractions' },
    { id: 5, name: 'Find and Rewrite All Documentation' },
    { id: 6, name: 'Generate React Components' },
    { id: 7, name: 'Deliver the Final Report' },
  ],
  tools: [
    { id: 'orgo_navigate', name: 'Navigate', category: 'Browser', description: 'Go to any URL in the controlled browser', icon: '🌐' },
    { id: 'orgo_screenshot', name: 'Screenshot', category: 'Browser', description: 'Capture the current screen state', icon: '📸' },
    { id: 'orgo_click', name: 'Click', category: 'Browser', description: 'Click any element by selector', icon: '👆' },
    { id: 'orgo_hover', name: 'Hover', category: 'Browser', description: 'Trigger hover states', icon: '🖱️' },
    { id: 'orgo_type', name: 'Type', category: 'Browser', description: 'Type into any field', icon: '⌨️' },
    { id: 'design_extract', name: 'Design Extractor', category: 'Analysis', description: 'Extract computed styles as design tokens', icon: '🎨' },
    { id: 'journey_mapper', name: 'Journey Mapper', category: 'Analysis', description: 'Document full user journey per page', icon: '🗺️' },
    { id: 'microinteraction_logger', name: 'Microinteraction Logger', category: 'Analysis', description: 'Log animation timing and CSS transitions', icon: '⚡' },
    { id: 'doc_rewriter', name: 'Doc Rewriter', category: 'Writing', description: 'Rewrite technical docs in plain language', icon: '✍️' },
    { id: 'component_gen', name: 'Component Generator', category: 'Code', description: 'Generate TypeScript React components from design tokens', icon: '🧩' },
  ],
  integrations: {
    'orgo-mcp': { enabled: true, via: 'mcp', fallback: 'webfetch' },
    'vercel-workflows': { enabled: true, via: 'step.run', purpose: 'checkpointing' },
    'claude-api': { enabled: true, via: 'direct', purpose: 'analysis and generation' },
    'superpowers': { enabled: true, via: 'registry' },
  },
  checkpointFile: '.checkpoint',
  guardrails: {
    maxPhaseMinutes: 5,
    maxCostUSD: 50,
    retryFailedActions: 1,
    neverStoreCredentials: true,
  },
};

export default UI_INTELLIGENCE_SKILL;
